version: '3.9'

volumes:
  postgresql_volume:

services:
  postgres:
    container_name: crm-postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'journal'
    ports:
      - 5432:5432
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
